# Generated by Django 4.1.1 on 2022-09-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpportfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_name', models.CharField(max_length=100)),
                ('publication_date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='')),
                ('project_body', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_body',
            field=models.TextField(),
        ),
    ]
