# Generated by Django 4.1.1 on 2022-09-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpportfolio', '0002_portfolio_alter_contact_contact_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('my_image', models.ImageField(upload_to='')),
                ('git_link', models.CharField(max_length=150)),
                ('e_mail', models.EmailField(max_length=254)),
                ('linked_link', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='git_link',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
