# Generated by Django 4.1.1 on 2022-09-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpportfolio', '0003_mycontact_portfolio_git_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile', models.CharField(max_length=1000)),
                ('skills', models.CharField(max_length=1000)),
                ('experience', models.CharField(max_length=1000)),
                ('education', models.CharField(max_length=1000)),
                ('hobby', models.CharField(max_length=1000)),
                ('other', models.CharField(max_length=1000)),
            ],
        ),
    ]
