# Generated by Django 4.1.1 on 2022-09-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpportfolio', '0004_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='education',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cv',
            name='experience',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cv',
            name='hobby',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cv',
            name='other',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cv',
            name='profile',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cv',
            name='skills',
            field=models.TextField(),
        ),
    ]
